version: "3.6"
services:
  # Web service layer
  nginx:
    image: nginx:1.13
    container_name: nginx-container
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - php

  # Application service layer
  php:
    build:
      context: docker/php
    container_name: php-container
    volumes:
      - ./:app:cached
    ports:
      - "9000:9000"
